# NOTE: contains intentional security test patterns for SAST/SCA/IaC scanning.
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template for an application

Resources:
  # FIX: Removed circular dependency by eliminating ReplicationConfiguration from AppBucket
  # The circular dependency was caused by AppBucket referencing ReplicationRole via !GetAtt,
  # while ReplicationRole referenced AppBucket via !GetAtt, creating a cycle.
  # Replication can be configured post-deployment or via separate stack if needed.
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-app-bucket-12345
      # FIX: Changed from PublicRead to Private to prevent public READ access (CWE-284)
      # This ensures the bucket ACL prohibits READ permission to everyone
      AccessControl: Private
      # Replication configuration removed to break circular dependency
      # To enable replication, configure it separately after stack creation or use a nested stack approach

  # IAM role for S3 replication
  # FIX: Modified to remove dependency on AppBucket to break the circular reference
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # FIX: Using explicit bucket name instead of !GetAtt to avoid circular dependency
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource: arn:aws:s3:::sample-app-bucket-12345
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource: arn:aws:s3:::sample-app-bucket-12345/*
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-replica/*'

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppFullPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'                       # Issue 2: wildcard action
                Resource: '*'                     # Issue 3: wildcard resource

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0                     # Issue 4: SSH open to the world
