# NOTE: contains intentional security test patterns for SAST/SCA/IaC scanning.
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template for an application

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-app-bucket-12345
      # FIX: Changed from PublicRead to Private to prevent public READ access (CWE-284)
      # This ensures the bucket ACL prohibits READ permission to everyone
      AccessControl: Private
      # FIX: Removed ReplicationConfiguration to break circular dependency
      # The ReplicationRole depends on AppBucket (via !GetAtt AppBucket.Arn)
      # and AppBucket was depending on ReplicationRole (via !GetAtt ReplicationRole.Arn)
      # To enable replication, create the role first, then add replication in a separate stack update
      VersioningConfiguration:
        Status: Enabled

  # IAM role for S3 replication
  # FIX: Removed references to AppBucket to break circular dependency
  # The role is now created independently and can be referenced later
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                # FIX: Using wildcard instead of !GetAtt to avoid circular dependency
                # In production, update this after stack creation with specific bucket ARN
                Resource: 'arn:aws:s3:::sample-app-bucket-12345'
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource: 'arn:aws:s3:::sample-app-bucket-12345/*'
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-replica/*'

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppFullPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'                       # Issue 2: wildcard action
                Resource: '*'                     # Issue 3: wildcard resource

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          # FIX: Restricted SSH access from 0.0.0.0/0 to a more secure CIDR range
          # Replace 10.0.0.0/8 with your organization's specific IP range or VPN CIDR
          CidrIp: 10.0.0.0/8                    # Restricted to private network range
