# NOTE: contains intentional security test patterns for SAST/SCA/IaC scanning.
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template for an application

Resources:
  # FIX: Moved AppBucket definition after ReplicationRole to break circular dependency
  # The circular dependency was caused by AppBucket referencing ReplicationRole.Arn (line 15)
  # while ReplicationRole referenced AppBucket.Arn (lines 45, 51)
  
  # IAM role for S3 replication - defined first to avoid circular dependency
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                # FIX: Changed from !GetAtt AppBucket.Arn to explicit bucket ARN construction
                # This breaks the circular dependency by using !Sub instead of !GetAtt
                Resource: !Sub 'arn:aws:s3:::sample-app-bucket-12345'
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                # FIX: Changed from !Sub '${AppBucket.Arn}/*' to explicit bucket ARN
                Resource: !Sub 'arn:aws:s3:::sample-app-bucket-12345/*'
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-replica/*'

  AppBucket:
    Type: AWS::S3::Bucket
    # FIX: Added DependsOn to ensure ReplicationRole is created first
    # This establishes a clear dependency order and prevents circular references
    DependsOn: ReplicationRole
    Properties:
      BucketName: sample-app-bucket-12345
      # FIX: Changed from PublicRead to Private to prevent public READ access (CWE-284)
      # This ensures the bucket ACL prohibits READ permission to everyone
      AccessControl: Private
      # FIX (CWE-284): Enabled versioning to address AWS Inspector finding - cloudformation-disabled-s3-versioning
      # Versioning protects against accidental deletion and provides object history for recovery
      VersioningConfiguration:
        Status: Enabled
      # Added cross-region replication configuration for improved data durability and availability
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Destination:
              Bucket: !Sub 'arn:aws:s3:::${AWS::StackName}-replica'
              Region: us-west-2  # Replication to a different region
            Status: Enabled
            Priority: 1
            DeleteMarkerReplication:
              Status: Enabled

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppFullPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'                       # Issue 2: wildcard action
                Resource: '*'                     # Issue 3: wildcard resource

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          # FIX: Restricted SSH access from 0.0.0.0/0 to a more secure CIDR range
          # Replace 10.0.0.0/8 with your organization's specific IP range or VPN CIDR
          CidrIp: 10.0.0.0/8                    # Restricted to private network range
